name = "cfsocial-api"
type = "javascript"

account_id = "f376fd342aa6769231f19a0947c482f4"
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2021-11-12"
kv_namespaces = [ 
  { binding = "POST", id = "4831b1476f484bfd91519c471aa8a6de" }
]
